openapi: 3.0.1
info:
  title: RequestBundleExample
  version: "1.0"
servers: []
tags:
- name: CustomerRelationshipManagement
  externalDocs:
    description: The role of this endpoint is Master Data Holder pattern
    url: https://api-patterns.org/patterns/responsibility/informationHolderEndpointTypes/MasterDataHolder.html
paths:
  /CustomerRelationshipManagement:
    summary: data-oriented endpoint, long-lived
    get:
      tags:
      - CustomerRelationshipManagement
      summary: read only
      description: This operation realizes the [Retrieval Operation](https://api-patterns.org/patterns/responsibility/operationResponsibilities/RetrievalOperation.html)
        pattern.
      operationId: lookupCustomers
      parameters:
      - name: Parameter1
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: lookupCustomers successful execution
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDTO'
    put:
      tags:
      - CustomerRelationshipManagement
      summary: write only
      description: This operation realizes the [State Creation Operation](https://api-patterns.org/patterns/responsibility/operationResponsibilities/StateCreationOperation.html)
        pattern.
      operationId: createCustomer
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        "200":
          description: createCustomer successful execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
    post:
      tags:
      - CustomerRelationshipManagement
      description: unspecified operation responsibility
      operationId: sendBulkRequest
      requestBody:
        content:
          application/json:
            schema:
              minItems: 1
              type: array
              items:
                $ref: '#/components/schemas/CustomerOperation'
      responses:
        "200":
          description: sendBulkRequest successful execution
          content:
            application/json:
              schema:
                minItems: 1
                type: array
                items:
                  $ref: '#/components/schemas/CustomerOperationResponse'
    patch:
      tags:
      - CustomerRelationshipManagement
      summary: read and write
      description: This operation realizes the [State Transition Operation](https://api-patterns.org/patterns/responsibility/operationResponsibilities/StateTransitionOperation.html)
        pattern.
      operationId: updateCustomer
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        "200":
          description: updateCustomer successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YesOrNo'
components:
  schemas:
    YesOrNo:
      type: object
      properties:
        anonymous1:
          type: boolean
    QueryExpression:
      type: object
      properties:
        anonymous2:
          type: string
    CustomerDTO:
      type: object
      properties:
        name:
          type: string
        contacts:
          type: array
          items:
            type: string
    CustomerOperation:
      type: object
      properties:
        createCustomer:
          $ref: '#/components/schemas/CustomerDTO'
        updateCustomer:
          $ref: '#/components/schemas/CustomerDTO'
        lookupCustomers:
          $ref: '#/components/schemas/QueryExpression'
    CustomerOperationResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        ok:
          $ref: '#/components/schemas/YesOrNo'
        results:
          type: array
          items:
            $ref: '#/components/schemas/CustomerDTO'
